"""
B-Roll Scout - Pydantic Models
Defines all request/response types and internal data structures.
"""

from pydantic import BaseModel, Field, ConfigDict, field_validator
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
import re


# ============================================================================
# Enums
# ============================================================================

class JobStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETE = "complete"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"


class TranscriptSource(str, Enum):
    CACHED = "cached_transcript"
    YOUTUBE_MANUAL = "youtube_captions"
    YOUTUBE_AUTO = "youtube_auto_captions"
    WHISPER = "whisper_transcription"
    NONE = "no_transcript"


# ============================================================================
# Request Models
# ============================================================================

class JobCreateRequest(BaseModel):
    """Request body for creating a new B-roll search job."""
    script: str = Field(..., min_length=100, description="Tamil script text")
    editor_id: str = Field(default="default_editor", description="Editor identifier")
    
    @field_validator("script")
    @classmethod
    def validate_script(cls, v: str) -> str:
        if len(v.strip()) < 100:
            raise ValueError("Script must be at least 100 characters")
        return v.strip()


class FeedbackRequest(BaseModel):
    """Request body for submitting feedback on a result."""
    rating: int = Field(..., ge=1, le=5, description="Rating from 1-5")
    clip_used: bool = Field(default=False, description="Whether the clip was used")
    notes: Optional[str] = Field(default=None, max_length=1000, description="Optional notes")


class SettingsUpdateRequest(BaseModel):
    """Request body for updating a single setting."""
    setting_key: str
    setting_value: Any


class BulkSettingsUpdateRequest(BaseModel):
    """Request body for bulk updating settings."""
    settings: Dict[str, Any]


class ChannelResolveRequest(BaseModel):
    """Request body for resolving a YouTube channel."""
    channel_url: str


# ============================================================================
# Segment Model
# ============================================================================

class Segment(BaseModel):
    """A script segment generated by the translator."""
    model_config = ConfigDict(from_attributes=True)
    
    segment_id: str = Field(..., pattern=r"^seg_\d{3}$")
    title: str
    summary: str
    visual_need: str
    emotional_tone: str
    key_terms: List[str] = Field(default_factory=list)
    search_queries: List[str] = Field(default_factory=list)
    estimated_duration_seconds: int = Field(default=60, ge=10)
    
    @field_validator("segment_id")
    @classmethod
    def validate_segment_id(cls, v: str) -> str:
        if not re.match(r"^seg_\d{3}$", v):
            raise ValueError("segment_id must match format seg_XXX")
        return v


# ============================================================================
# Video and Result Models
# ============================================================================

class CandidateVideo(BaseModel):
    """A candidate video found by the searcher."""
    model_config = ConfigDict(from_attributes=True)
    
    video_id: str
    video_url: str
    video_title: str
    channel_name: str
    channel_id: str
    channel_subscribers: int = 0
    thumbnail_url: str
    video_duration_seconds: int
    published_at: str
    view_count: int = 0
    is_preferred_tier1: bool = False
    is_preferred_tier2: bool = False
    is_blocked: bool = False


class TimestampMatchResult(BaseModel):
    """Timestamp match result from the matcher (DynamoDB layer)."""
    model_config = ConfigDict(from_attributes=True)
    
    start_time_seconds: Optional[int] = None
    end_time_seconds: Optional[int] = None
    transcript_excerpt: Optional[str] = None
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    relevance_note: Optional[str] = None
    the_hook: Optional[str] = None
    source_flag: TranscriptSource = TranscriptSource.NONE
    context_match_valid: bool = True


class RankedResult(BaseModel):
    """Final ranked result ready for output."""
    model_config = ConfigDict(from_attributes=True)
    
    result_id: str
    segment_id: str
    video_id: str
    video_url: str
    video_title: str
    channel_name: str
    channel_subscribers: int = 0
    thumbnail_url: str
    video_duration_seconds: int
    published_at: str
    view_count: int = 0
    start_time_seconds: Optional[int] = None
    end_time_seconds: Optional[int] = None
    clip_url: Optional[str] = None
    transcript_excerpt: Optional[str] = None
    the_hook: Optional[str] = None
    relevance_score: float = Field(default=0.0, ge=0.0, le=1.0)
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    source_flag: TranscriptSource = TranscriptSource.NONE
    editor_rating: Optional[int] = Field(default=None, ge=1, le=5)
    clip_used: bool = False
    editor_notes: Optional[str] = None


# ============================================================================
# Transcript Model
# ============================================================================

class Transcript(BaseModel):
    """Cached transcript data."""
    model_config = ConfigDict(from_attributes=True)
    
    video_id: str
    transcript_text: Optional[str] = None
    transcript_source: TranscriptSource
    language: str = "en"
    video_duration_seconds: int = 0
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ============================================================================
# API Cost Tracking
# ============================================================================

class APICosts(BaseModel):
    """Tracks API usage and costs for a job."""
    openai_calls: int = 0
    openai_mini_calls: int = 0
    openai_input_tokens: int = 0
    openai_output_tokens: int = 0
    whisper_minutes: float = 0.0
    youtube_api_units: int = 0
    google_cse_calls: int = 0
    gemini_calls: int = 0
    estimated_cost_usd: float = 0.0


# ============================================================================
# Job Response Models
# ============================================================================

class SegmentWithResults(Segment):
    """Segment with its associated results."""
    results: List[RankedResult] = Field(default_factory=list)


class JobResponse(BaseModel):
    """Full job response with all segments and results."""
    model_config = ConfigDict(from_attributes=True)
    
    job_id: str
    status: JobStatus
    created_at: str
    completed_at: Optional[str] = None
    processing_time_seconds: Optional[float] = None
    script_duration_minutes: int = 0
    total_segments: int = 0
    total_results: int = 0
    minimum_results_met: bool = True
    api_costs: APICosts = Field(default_factory=APICosts)
    segments: List[SegmentWithResults] = Field(default_factory=list)
    english_translation: Optional[str] = None


class JobSummary(BaseModel):
    """Summary info for job listing."""
    job_id: str
    status: JobStatus
    created_at: str
    segment_count: int = 0
    result_count: int = 0


class JobListResponse(BaseModel):
    """Response for listing jobs."""
    jobs: List[JobSummary] = Field(default_factory=list)


# ============================================================================
# Settings Models
# ============================================================================

class ChannelResolution(BaseModel):
    """Resolved YouTube channel metadata."""
    channel_id: str
    channel_name: str
    subscribers: int = 0
    thumbnail_url: str = ""


class SettingsResponse(BaseModel):
    """All settings as a flat dictionary."""
    settings: Dict[str, Any]


# ============================================================================
# Health Check
# ============================================================================

class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "ok"
    db: str = "connected"
    version: str = "0.1.0"


# ============================================================================
# Library Search
# ============================================================================

class LibrarySearchParams(BaseModel):
    """Query parameters for library search."""
    topic: Optional[str] = None
    date_from: Optional[str] = None
    min_rating: Optional[int] = Field(default=None, ge=1, le=5)


class LibrarySearchResponse(BaseModel):
    """Response for library search."""
    results: List[RankedResult] = Field(default_factory=list)
    total_count: int = 0


# ============================================================================
# Visual Cue & Pipeline Models (used by services)
# ============================================================================

class VisualCue(BaseModel):
    """A visual cue generated by the translator from script analysis."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    timestamp_start: float = 0.0
    timestamp_end: float = 0.0
    script_excerpt: str = ""
    visual_description: str = ""
    search_queries: List[str] = Field(default_factory=list)
    mood: str = "neutral"
    priority: str = "medium"
    notes: str = ""
    status: str = "pending"


class TranslationResult(BaseModel):
    """Result from the translator service."""
    visual_cues: List[VisualCue] = Field(default_factory=list)
    total_cues: int = 0
    estimated_duration: float = 0.0
    cost: float = 0.0
    model_used: str = ""


class StockClip(BaseModel):
    """A stock footage clip from a search provider."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    source: str = "pexels"
    title: str = ""
    description: str = ""
    duration: float = 0.0
    preview_url: Optional[str] = None
    download_url: Optional[str] = None
    width: int = 1920
    height: int = 1080
    fps: int = 30
    file_type: str = "video/mp4"
    author: str = ""
    author_url: str = ""
    license: str = ""
    tags: List[str] = Field(default_factory=list)
    quality: str = "HD"
    source_query: Optional[str] = None
    cue_id: Optional[str] = None
    mood_match: Optional[str] = None
    relevance_score: Optional[float] = None
    match_reasons: Optional[List[str]] = None
    analysis: Optional[Any] = None


class SearchResult(BaseModel):
    """Result from a stock footage search."""
    cue_id: str
    clips: List[StockClip] = Field(default_factory=list)
    total_results: int = 0
    queries_executed: List[str] = Field(default_factory=list)
    search_timestamp: str = ""


class ClipAnalysis(BaseModel):
    """Analysis of a clip's match to a visual cue."""
    clip_id: str
    cue_id: str
    relevance_score: float = 0.5
    match_reasons: List[str] = Field(default_factory=list)
    mood_match: bool = False
    duration_suitable: bool = True
    quality_assessment: str = "fair"
    concerns: List[str] = Field(default_factory=list)
    recommendation: str = "weak_match"


class MatchResult(BaseModel):
    """Result from the matcher service (service-level)."""
    cue_id: str
    matches: List[StockClip] = Field(default_factory=list)
    total_analyzed: int = 0


class SelectionPreferences(BaseModel):
    """User preferences for clip selection."""
    min_quality: Optional[str] = None
    preferred_sources: List[str] = Field(default_factory=list)
    preferred_moods: List[str] = Field(default_factory=list)
    max_alternatives: int = 3
    min_duration: Optional[float] = None


class RankedSelection(BaseModel):
    """A ranked selection of a clip for a cue."""
    cue_id: str
    selected_clip: Optional[StockClip] = None
    alternatives: List[StockClip] = Field(default_factory=list)
    ranking_scores: Dict[str, float] = Field(default_factory=dict)
    final_score: Optional[float] = None
    selection_reason: str = ""


class JobProgress(BaseModel):
    """Progress tracking for a job."""
    current_stage: str = "initialized"
    percent_complete: int = 0
    message: str = ""


class Job(BaseModel):
    """Full job model used by the orchestrator and API."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    status: JobStatus = JobStatus.PROCESSING
    stage: str = "initialized"
    script_text: str = ""
    video_style: str = "documentary"
    target_audience: str = "general"
    preferences: SelectionPreferences = Field(default_factory=SelectionPreferences)
    created_at: str = ""
    completed_at: Optional[str] = None
    progress: Optional[JobProgress] = None
    visual_cues: List[VisualCue] = Field(default_factory=list)
    search_results: Optional[List[SearchResult]] = None
    match_results: Optional[Dict[str, MatchResult]] = None
    selections: Optional[Dict[str, RankedSelection]] = None
    summary: Optional[Dict[str, Any]] = None
    total_cost: float = 0.0
    error: Optional[str] = None


class PipelineResult(BaseModel):
    """Result from the complete pipeline run."""
    job_id: str
    status: JobStatus
    visual_cues: List[VisualCue] = Field(default_factory=list)
    selections: Dict[str, RankedSelection] = Field(default_factory=dict)
    summary: Optional[Dict[str, Any]] = None
    total_cost: float = 0.0


class TranscriptionSegment(BaseModel):
    """A segment from Whisper transcription."""
    id: int = 0
    start: float = 0.0
    end: float = 0.0
    text: str = ""


class TranscriptionResult(BaseModel):
    """Result from the transcriber service."""
    text: str = ""
    segments: List[TranscriptionSegment] = Field(default_factory=list)
    language: str = "en"
    duration: float = 0.0
    cost: float = 0.0
